### ISSUE TITLE
Create mockup of dashboard

### ISSUE THREAD

**Issue by Jordan-Parra** [Jordan-Parra/nightowl#3]
- Discern content, preexisting systems in attempt to emulate uniform visual style.

**Comment by theroguemuppet** [comment]
Vincent had the great idea to go through and look at invisionapp.com; checking it out as we speak. Looks like it'll be a great tool as we progress through the development process. 

Per our previous conversations, I am going to make the first pass at the design piece. When I have a deliverable for review, I will post a link below this comment. Cheers, all! :)
