### ISSUE TITLE
InvisionApp Demo!!

### ISSUE THREAD

**Issue by theroguemuppet** [Jordan-Parra/nightowl#7]
Hey gang!! Take a look at this: 

http://invis.io/RQ23S4JUW

This is the first round of the mock-up for the dashboard. I went through and constructed (with Jordan's feedback) the first pass at the design! Vincent, because you identified InvisionApp, I feel like you're better at navigating it than myself!! Would you like to take a look at it and help us from here?

Thanks all!!

-R

**Comment by vietcent** [comment]
can you share this with me so i can make edits as well?

_--_
_Vincent Q. Nguyen_

_B.S Computer Information SystemsW.P Carey School of Business, Arizona
State University_
_Vice President of Community Service for DISC Club_
(623)-498-7538 *| *vqnguyen16@gmail.com
